config/routes.rb
RandysEcommerceStore::Application.routes.draw do
  resources :cart_items

  root :to => 'products#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :provinces
  resources :products
  resources :orders
  resources :line_items
  resources :customers
  resources :platforms
  resources :contact_us
  resources :about_us

  match "/search_results" => "products#search_results"
  match "/sales" => "products#sales"
  match "/recently_updated" => "products#recently_updated"
  match "/login" => "customers#login"
  match "/login_form" => "customers#login_form"
  match "/register" => "customers#new"
  match "/logout" => "customers#logout"

end

app/models/about_u.rb
class AboutU < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  attr_accessible :customer_id, :product_id, :quantity
end

app/models/contact_u.rb
class ContactU < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :address, :city, :country, :email, :name, :postal_code, :province_id, :password
  validates_presence_of :address, :city, :country, :email, :postal_code, :province_id
  belongs_to :province
  has_many :orders
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :order_id, :price, :product_id, :quantity
  belongs_to :product
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :customer_id, :gst, :hst, :payment_identifier, :payment_processor, :pst, :status, :subtotal, :total
  belongs_to :customer
end

app/models/platform.rb
class Platform < ActiveRecord::Base
  attr_accessible :description, :image, :name
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :platform_id, :price, :stock_quantity, :image, :on_sale, :sale_price
  belongs_to :platform
  has_many :line_items
end

app/models/province.rb
class Province < ActiveRecord::Base
  attr_accessible :code, :gst, :home_province, :hst, :name, :pst
  has_many :customers
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  # GET /platforms
  # GET /platforms.json
  def index
    @platforms = Platform.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @platforms }
    end
  end

  # GET /platforms/1
  # GET /platforms/1.json
  def show
    @platform = Platform.find(params[:id])
    @products = Product.where("platform_id = #{@platform.id}")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @platform }
    end
  end

  # GET /platforms/new
  # GET /platforms/new.json
  def new
    @platform = Platform.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @platform }
    end
  end

  # GET /platforms/1/edit
  def edit
    @platform = Platform.find(params[:id])
  end

  # POST /platforms
  # POST /platforms.json
  def create
    @platform = Platform.new(params[:platform])

    respond_to do |format|
      if @platform.save
        format.html { redirect_to @platform, notice: 'Platform was successfully created.' }
        format.json { render json: @platform, status: :created, location: @platform }
      else
        format.html { render action: "new" }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /platforms/1
  # PUT /platforms/1.json
  def update
    @platform = Platform.find(params[:id])

    respond_to do |format|
      if @platform.update_attributes(params[:platform])
        format.html { redirect_to @platform, notice: 'Platform was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platforms/1
  # DELETE /platforms/1.json
  def destroy
    @platform = Platform.find(params[:id])
    @platform.destroy

    respond_to do |format|
      format.html { redirect_to platforms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/platforms/_form.html.erb
<%= form_for(@platform) do |f| %>
  <% if @platform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@platform.errors.count, "error") %> prohibited this platform from being saved:</h2>

      <ul>
      <% @platform.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/platforms/edit.html.erb
<h1>Editing platform</h1>

<%= render 'form' %>

<%= link_to 'Show', @platform %> |
<%= link_to 'Back', platforms_path %>

app/views/platforms/index.html.erb
<h1>Listing platforms</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @platforms.each do |platform| %>
  <tr>
    <td><%= platform.name %></td>
    <td><%= platform.image %></td>
    <td><%= platform.description %></td>
    <td><%= link_to 'Show', platform %></td>
    <td><%= link_to 'Edit', edit_platform_path(platform) %></td>
    <td><%= link_to 'Destroy', platform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Platform', new_platform_path %>

app/views/platforms/new.html.erb
<h1>New platform</h1>

<%= render 'form' %>

<%= link_to 'Back', platforms_path %>

app/views/platforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @platform.name %>
</p>

<p>
  <b>Image:</b>
  <%= @platform.image %>
</p>

<p>
  <b>Description:</b>
  <%= @platform.description %>
</p>


<%= link_to 'Edit', edit_platform_path(@platform) %> |
<%= link_to 'Back', platforms_path %>